# Generated by Django 3.2.7 on 2021-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crunches',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('reps', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plank',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pullups',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('reps', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pushups',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('reps', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('high_alt', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Three_Mile',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('high_alt', models.CharField(max_length=10)),
            ],
        ),
    ]
