# Generated by Django 3.2.7 on 2021-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo_Lift',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('reps', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maneuver_Fire',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('time', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('high_alt', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movement_Contact',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=3)),
                ('time', models.CharField(max_length=10)),
                ('score', models.CharField(max_length=10)),
                ('high_alt', models.CharField(max_length=20)),
            ],
        ),
    ]
